use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use std::path::Path;

fn noagents(root: &Path) -> Command {
    let mut cmd = Command::cargo_bin("noagents").unwrap();
    cmd.current_dir(root);
    cmd
}

fn read(root: &Path, rel: &str) -> String {
    fs::read_to_string(root.join(rel)).unwrap_or_else(|_| panic!("missing {rel}"))
}

fn init_and_generate(root: &Path) {
    noagents(root).arg("init").assert().success();
    noagents(root).arg("generate").assert().success();
}

#[test]
fn init_then_generate_creates_all_default_files() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_and_generate(root);

    for f in [
        ".cursorignore",
        ".codeiumignore",
        ".aiderignore",
        ".aiignore",
        ".aiexclude",
        ".geminiignore",
        ".continueignore",
        ".clineignore",
        ".rooignore",
        ".tabnineignore",
        ".augmentignore",
        ".kilocodeignore",
        ".gooseignore",
        ".kiroignore",
        ".trae/.ignore",
        ".claude/settings.json",
        ".zed/settings.json",
        ".ai_config.toml",
        ".noagents.state",
    ] {
        assert!(root.join(f).is_file(), "expected {f}");
    }
    // opt-in target not generated by default
    assert!(!root.join(".cursorindexingignore").exists());

    let cursor = read(root, ".cursorignore");
    assert!(cursor.contains(".env"));
    assert!(cursor.contains("noagents managed"));
    // negation kept where supported, dropped where not
    assert!(cursor.contains("!.env.example"));
    assert!(!read(root, ".aiexclude").contains("!.env.example"));

    let claude = read(root, ".claude/settings.json");
    assert!(claude.contains("Read(./.env)"));
    assert!(claude.contains("Read(./**/secrets/**)"));
}

#[test]
fn generate_is_idempotent() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_and_generate(root);
    let before = read(root, ".cursorignore");
    let before_claude = read(root, ".claude/settings.json");

    noagents(root)
        .arg("generate")
        .assert()
        .success()
        .stdout(predicate::str::contains("created").not());
    assert_eq!(before, read(root, ".cursorignore"));
    assert_eq!(before_claude, read(root, ".claude/settings.json"));
}

#[test]
fn preserves_user_content_and_merges() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::write(root.join(".cursorignore"), "user-pattern\n").unwrap();
    fs::create_dir_all(root.join(".claude")).unwrap();
    fs::write(
        root.join(".claude/settings.json"),
        r#"{"model": "opus", "permissions": {"allow": ["Bash(ls:*)"]}}"#,
    )
    .unwrap();

    init_and_generate(root);

    let cursor = read(root, ".cursorignore");
    assert!(cursor.starts_with("user-pattern\n"));
    assert!(cursor.contains(".env"));

    let claude = read(root, ".claude/settings.json");
    assert!(claude.contains("\"model\""));
    assert!(claude.contains("Bash(ls:*)"));
    assert!(claude.contains("Read(./.env)"));
}

#[test]
fn config_edit_regenerate_drops_stale_entries() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::write(root.join(".noagents"), "old-secret/\n").unwrap();
    noagents(root).arg("generate").assert().success();
    assert!(read(root, ".cursorignore").contains("old-secret/"));
    assert!(read(root, ".claude/settings.json").contains("old-secret"));

    fs::write(root.join(".noagents"), "new-secret/\n").unwrap();
    noagents(root).arg("generate").assert().success();

    let cursor = read(root, ".cursorignore");
    assert!(!cursor.contains("old-secret"));
    assert!(cursor.contains("new-secret/"));
    let claude = read(root, ".claude/settings.json");
    assert!(!claude.contains("old-secret"), "stale deny entries removed");
    assert!(claude.contains("new-secret"));
}

#[test]
fn add_appends_and_regenerates() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_and_generate(root);

    noagents(root)
        .args(["add", "my-private-dir/"])
        .assert()
        .success();
    assert!(read(root, ".noagents").contains("my-private-dir/"));
    assert!(read(root, ".cursorignore").contains("my-private-dir/"));

    // duplicate add is a no-op
    noagents(root)
        .args(["add", "my-private-dir/"])
        .assert()
        .success()
        .stdout(predicate::str::contains("added 0 pattern(s)"));
}

#[test]
fn remove_restores_pre_existing_content() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    let original_cursor = "user-pattern\n*.log\n";
    fs::write(root.join(".cursorignore"), original_cursor).unwrap();
    fs::create_dir_all(root.join(".claude")).unwrap();
    let original_claude = r#"{"model": "opus"}"#;
    fs::write(root.join(".claude/settings.json"), original_claude).unwrap();

    init_and_generate(root);
    noagents(root).arg("remove").assert().success();

    assert_eq!(read(root, ".cursorignore"), original_cursor);
    let claude = read(root, ".claude/settings.json");
    assert!(claude.contains("\"model\""));
    assert!(!claude.contains("Read("));
    // files we created are deleted again, including now-empty dirs
    assert!(!root.join(".aiderignore").exists());
    assert!(!root.join(".zed").exists());
    assert!(!root.join(".trae").exists());
    assert!(root.join(".claude").exists(), "pre-existing dir kept");
    assert!(!root.join(".noagents.state").exists());
}

#[test]
fn remove_preserves_pre_existing_empty_user_dir() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    // User created an empty .zed/ but no settings file.
    fs::create_dir_all(root.join(".zed")).unwrap();
    init_and_generate(root);
    assert!(root.join(".zed/settings.json").is_file());

    noagents(root).arg("remove").assert().success();
    // File we created is gone, but the directory the user made stays.
    assert!(!root.join(".zed/settings.json").exists());
    assert!(root.join(".zed").is_dir(), "user's dir must survive");
}

#[test]
fn remove_works_after_state_file_deleted() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".claude")).unwrap();
    fs::write(root.join(".claude/settings.json"), r#"{"model": "opus"}"#).unwrap();
    init_and_generate(root);
    assert!(read(root, ".claude/settings.json").contains("Read("));

    // Simulate the sidecar being lost (e.g. not committed / deleted).
    fs::remove_file(root.join(".noagents.state")).unwrap();

    noagents(root).arg("remove").assert().success();
    let claude = read(root, ".claude/settings.json");
    assert!(
        !claude.contains("Read("),
        "our entries stripped via config fallback"
    );
    assert!(claude.contains("\"model\""), "user content preserved");
}

#[test]
fn remove_leaves_untouched_structured_file_unchanged() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();
    // Only generate line targets, so no entries land in Claude's settings.
    noagents(root)
        .args(["generate", "--only", "cursor"])
        .assert()
        .success();
    let original = "{\n  \"model\": \"opus\"\n}\n";
    fs::create_dir_all(root.join(".claude")).unwrap();
    fs::write(root.join(".claude/settings.json"), original).unwrap();

    noagents(root).arg("remove").assert().success();
    // Claude file had none of our entries: byte-identical, no reformat churn.
    assert_eq!(read(root, ".claude/settings.json"), original);
}

#[test]
fn check_detects_drift() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_and_generate(root);

    noagents(root).arg("check").assert().success();

    // tamper with a generated file
    let path = root.join(".cursorignore");
    let mut text = fs::read_to_string(&path).unwrap();
    text = text.replace(".env", ".tampered");
    fs::write(&path, text).unwrap();

    noagents(root)
        .arg("check")
        .assert()
        .code(1)
        .stdout(predicate::str::contains("DRIFT: cursor"));
}

#[test]
fn dry_run_writes_nothing() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();
    noagents(root)
        .args(["generate", "--dry-run"])
        .assert()
        .success()
        .stdout(predicate::str::contains("+++ .cursorignore"));
    assert!(!root.join(".cursorignore").exists());
    assert!(!root.join(".noagents.state").exists());
}

#[test]
fn only_and_exclude_select_targets() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();

    noagents(root)
        .args(["generate", "--only", "cursor,aider"])
        .assert()
        .success();
    assert!(root.join(".cursorignore").is_file());
    assert!(root.join(".aiderignore").is_file());
    assert!(!root.join(".clineignore").exists());

    noagents(root)
        .args(["generate", "--exclude", "cline"])
        .assert()
        .success();
    assert!(!root.join(".clineignore").exists());
    assert!(root.join(".rooignore").is_file());

    noagents(root)
        .args(["generate", "--only", "bogus"])
        .assert()
        .code(2);
}

#[test]
fn generate_without_config_exits_2() {
    let tmp = tempfile::tempdir().unwrap();
    noagents(tmp.path())
        .arg("generate")
        .assert()
        .code(2)
        .stderr(predicate::str::contains("noagents init"));
}

#[test]
fn init_twice_needs_force() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();
    noagents(root).arg("init").assert().code(2);
    noagents(root).args(["init", "--force"]).assert().success();
}

#[test]
fn jsonc_settings_skipped_not_destroyed() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".zed")).unwrap();
    let jsonc = "// zed config\n{\n  \"theme\": \"dark\"\n}\n";
    fs::write(root.join(".zed/settings.json"), jsonc).unwrap();

    init_and_generate(root);
    // untouched, and the run still succeeded for other targets
    assert_eq!(read(root, ".zed/settings.json"), jsonc);
    assert!(root.join(".cursorignore").is_file());
}

#[test]
fn snapshot_all_rendered_outputs() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::write(
        root.join(".noagents"),
        ".env\n!.env.example\n*.pem\nsecrets/\n/anchored/dir/\n",
    )
    .unwrap();
    noagents(root).arg("generate").assert().success();

    let mut out = String::new();
    let mut files: Vec<_> = walk(root)
        .into_iter()
        .filter(|p| p.file_name().unwrap() != ".noagents")
        .collect();
    files.sort();
    for f in &files {
        let rel = f.strip_prefix(root).unwrap();
        // Normalize separators so the snapshot is stable across OSes.
        let rel = rel.to_string_lossy().replace('\\', "/");
        out.push_str(&format!("===== {rel} =====\n"));
        out.push_str(&fs::read_to_string(f).unwrap());
        out.push('\n');
    }
    insta::assert_snapshot!("all_targets", out);
}

#[test]
fn status_reports_in_sync_stale_and_missing() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_and_generate(root);

    // fresh generate → everything in-sync
    noagents(root)
        .arg("status")
        .assert()
        .success()
        .stdout(predicate::str::contains("in-sync").and(predicate::str::contains("stale").not()));

    // delete one file → missing; tamper another → stale
    fs::remove_file(root.join(".aiderignore")).unwrap();
    let mut cursor = fs::read_to_string(root.join(".cursorignore")).unwrap();
    cursor = cursor.replace(".env", ".tampered");
    fs::write(root.join(".cursorignore"), cursor).unwrap();

    noagents(root).arg("status").assert().success().stdout(
        predicate::str::contains("missing")
            .and(predicate::str::contains("stale"))
            .and(predicate::str::contains("aider"))
            .and(predicate::str::contains("cursor")),
    );
    // status never changes exit code, even with drift
}

#[test]
fn list_shows_targets_and_presence() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();
    noagents(root)
        .args(["generate", "--only", "cursor"])
        .assert()
        .success();

    noagents(root).arg("list").assert().success().stdout(
        predicate::str::contains("claude-code")
            .and(predicate::str::contains(".cursorignore"))
            .and(predicate::str::contains("copilot"))
            .and(predicate::str::contains("advisory")),
    );
}

#[test]
fn add_multiple_patterns_reach_every_family() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::write(root.join(".noagents"), "seed\n").unwrap();
    noagents(root).arg("generate").assert().success();

    noagents(root)
        .args(["add", "vault/", "*.token"])
        .assert()
        .success()
        .stdout(predicate::str::contains("added 2 pattern(s)"));

    // line family
    assert!(read(root, ".cursorignore").contains("vault/"));
    assert!(read(root, ".cursorignore").contains("*.token"));
    // json family (Claude deny + Zed globs)
    let claude = read(root, ".claude/settings.json");
    assert!(claude.contains("Read(./vault/**)"));
    assert!(claude.contains("Read(./*.token)"));
    let zed = read(root, ".zed/settings.json");
    assert!(zed.contains("**/vault/**"));
    assert!(zed.contains("**/*.token"));
    // toml family
    let qodo = read(root, ".ai_config.toml");
    assert!(qodo.contains("**/vault/**"));
    assert!(qodo.contains("**/*.token"));
}

#[test]
fn add_invalid_pattern_exits_2() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();
    noagents(root).args(["add", "   "]).assert().code(2);
    // a comment-only token is not a real pattern
    noagents(root).args(["add", "# nope"]).assert().code(2);
}

#[test]
fn add_without_config_exits_2() {
    let tmp = tempfile::tempdir().unwrap();
    noagents(tmp.path())
        .args(["add", ".env"])
        .assert()
        .code(2)
        .stderr(predicate::str::contains("noagents init"));
}

#[test]
fn corrupt_state_file_exits_1() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();
    fs::write(root.join(".noagents.state"), "{ not json").unwrap();
    noagents(root)
        .arg("generate")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("corrupted"));
}

#[test]
fn corrupt_managed_block_skips_target_not_run() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    noagents(root).arg("init").assert().success();
    // only the start marker present → corrupted
    fs::write(
        root.join(".cursorignore"),
        "# >>> noagents managed — DO NOT EDIT; run `noagents generate` >>>\n.env\n",
    )
    .unwrap();

    noagents(root)
        .arg("generate")
        .assert()
        .success() // other targets still generated
        .stderr(predicate::str::contains("skipped").and(predicate::str::contains("cursor")));
    // sibling target unaffected
    assert!(read(root, ".aiderignore").contains(".env"));
}

#[test]
fn aiexclude_drops_negations_but_keeps_rest() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::write(root.join(".noagents"), ".env\n!.env.example\nsecrets/\n").unwrap();
    noagents(root)
        .arg("generate")
        .assert()
        .success()
        .stderr(predicate::str::contains("negated pattern"));

    let aiexclude = read(root, ".aiexclude");
    assert!(aiexclude.contains(".env"));
    assert!(aiexclude.contains("secrets/"));
    assert!(!aiexclude.contains("!.env.example"));
    // but a negation-supporting target keeps it
    assert!(read(root, ".cursorignore").contains("!.env.example"));
}

#[test]
fn qodo_preserves_user_toml_comments() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::write(root.join(".noagents"), ".env\n").unwrap();
    let user_toml = "# my qodo config\n[file_filters]\ninclude = [\"src/**\"]\n";
    fs::write(root.join(".ai_config.toml"), user_toml).unwrap();

    noagents(root).arg("generate").assert().success();
    let out = read(root, ".ai_config.toml");
    assert!(out.contains("# my qodo config"), "user comment kept");
    assert!(out.contains("include = [\"src/**\"]"), "user key kept");
    assert!(out.contains("**/.env"), "our exclude added");
}

#[test]
fn cursor_index_is_opt_in_only() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_and_generate(root);
    assert!(!root.join(".cursorindexingignore").exists());

    noagents(root)
        .args(["generate", "--only", "cursor-index"])
        .assert()
        .success();
    assert!(root.join(".cursorindexingignore").is_file());
}

#[test]
fn root_flag_targets_other_directory() {
    let tmp = tempfile::tempdir().unwrap();
    let outer = tmp.path();
    let proj = outer.join("proj");
    fs::create_dir_all(&proj).unwrap();
    fs::write(proj.join(".noagents"), ".env\n").unwrap();

    // run from outer, point --root at proj
    noagents(outer)
        .args(["generate", "--root"])
        .arg(&proj)
        .assert()
        .success();
    assert!(proj.join(".cursorignore").is_file());
    assert!(!outer.join(".cursorignore").exists());
}

#[test]
fn line_target_preserves_content_before_and_after_block() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    fs::write(root.join(".noagents"), ".env\n").unwrap();
    // pre-existing file with content the block will land between/around
    fs::write(root.join(".cursorignore"), "top-rule\n").unwrap();
    noagents(root).arg("generate").assert().success();

    // append a trailing user rule after the managed block, then regenerate
    let mut c = fs::read_to_string(root.join(".cursorignore")).unwrap();
    c.push_str("bottom-rule\n");
    fs::write(root.join(".cursorignore"), &c).unwrap();

    fs::write(root.join(".noagents"), ".env\nnewrule\n").unwrap();
    noagents(root).arg("generate").assert().success();

    let out = read(root, ".cursorignore");
    assert!(out.starts_with("top-rule\n"));
    assert!(out.trim_end().ends_with("bottom-rule"));
    assert!(out.contains("newrule"));
}

#[test]
fn check_quiet_still_reports_drift_lines() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    init_and_generate(root);
    fs::remove_file(root.join(".cursorignore")).unwrap();

    noagents(root)
        .args(["check", "--quiet"])
        .assert()
        .code(1)
        .stdout(predicate::str::contains("DRIFT: cursor"));
}

fn walk(dir: &Path) -> Vec<std::path::PathBuf> {
    let mut out = Vec::new();
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        if path.is_dir() {
            out.extend(walk(&path));
        } else {
            out.push(path);
        }
    }
    out
}
